### PR TITLE
Updated application to use Spring

### PR DESCRIPTION
**Pull request by SynverseSageOne**

### CODE REVIEW

**Comment by adamgeorgeson** [comment]
I'd target v3 branch. Master is still relevant for v1 and v2.

**Comment by adamgeorgeson** [comment]
I'm going to close this for now and link to it from the main readme so we have a couple of examples. Reasoning for this is a developer I've been working with preferred the non-Spring example so don't want to take this away from him whilst he's integrating with v3.

**Comment by chrisbarber86** [comment]
@SynverseSageOne @adamgeorgeson Would it make sense for us to create a new `sageone_api_spring_example` repo instead? Since they're quite different.

**Comment by adamgeorgeson** [comment]
@chrisbarber86 Yeah, I think we should. Is that something you can arrange and I'll get this code pushed there?

**Comment by chrisbarber86** [comment]
@adamgeorgeson Yup I'll arrange that.

**Comment by chrisbarber86** [comment]
@adamgeorgeson @SynverseSageOne Done: https://github.com/Sage/sageone_api_spring_sample

**Pull request closed without merging**
